//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppForMED.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyNewMedWebEntities2 : DbContext
    {
        public MyNewMedWebEntities2()
            : base("name=MyNewMedWebEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<DocRecord> DocRecords { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<FreeTime> FreeTimes { get; set; }
        public virtual DbSet<Illness> Illnesses { get; set; }
        public virtual DbSet<MedCard> MedCards { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<WorkTime> WorkTimes { get; set; }
    }
}
